### ISSUE TITLE
kills web browser

### ISSUE THREAD

**Issue by hannahtardie** [hannahtardie/icmfinal#1]
it is nearly impossible to make it through the entire sketch without the browser dying and having to reload. 
i tried to putting functions in separate .js files but that hasn't helped.
i also even hand wrote out some stuff because i noticed that for loops like this  for "(let i = 0; i < 10; i++) {}" were making the load time slow. Any ideas for why the load time is so slow? 
my guess is that it has to do with the Cube Class Constructor.

**Comment by koji** [comment]
@hannahtardie 
Can you update your index.html? index.html isn't working properly and I don't know how you want to call your js files.

I checked your second and third sketch which has sliders. I think you don't need to create separate files for functions.

also missing some images files.

**Comment by hannahtardie** [comment]
@sleepy-maker sorry about that -- i just added a new repo and directly uploaded the files from my p5 download, everything should be in there now and i added you as a collaborator so you should see it soon
